### ISSUE TITLE
[mobile] Страница form:  Убрать лишний отступ у последнего элемента

### ISSUE THREAD

**Issue by alexbaumgertner** [up-htmlacademy/61579-pink#15]
@insanegrv 

![screenshot at oct 28 22-47-12](https://cloud.githubusercontent.com/assets/223620/10800948/f5635f68-7dc5-11e5-82fe-a0dab2fed2a1.png)

**Comment by alexbaumgertner** [comment]
Тут все просто: `last-child { magrin-bottom: 0 }`

**Comment by insanegrv** [comment]
Исправил в  https://github.com/up-htmlacademy/61579-pink/pull/20#issuecomment-152445906

**Comment by alexbaumgertner** [comment]
:ok:
