### ISSUE TITLE
[mobile] Страница form:  Поправить размер полей ввода

### ISSUE THREAD

**Issue by alexbaumgertner** [up-htmlacademy/61579-pink#16]
@insanegrv 

![screenshot at oct 28 22-49-48](https://cloud.githubusercontent.com/assets/223620/10801229/65e854f4-7dc7-11e5-90c9-05634a9ca7fd.png)

**Comment by alexbaumgertner** [comment]
Тут или padding или font-size больше нужного

**Comment by insanegrv** [comment]
Исправил в https://github.com/up-htmlacademy/61579-pink/pull/20

**Comment by alexbaumgertner** [comment]
Большие padding, посмотри внимательно с макетом:

![screenshot at oct 30 16-52-27](https://cloud.githubusercontent.com/assets/223620/10847320/a06375ae-7f26-11e5-9b71-48bf76fa117d.png)

**Comment by alexbaumgertner** [comment]
Да, теперь супер!

![screen shot 2015-10-30 at 21 04 17](https://cloud.githubusercontent.com/assets/223620/10853921/d8aab670-7f49-11e5-8e63-c90e3828be9d.png)
