### ISSUE TITLE
[mobile] Страница form: Поправить цвет кнопок

### ISSUE THREAD

**Issue by alexbaumgertner** [up-htmlacademy/61579-pink#17]
@insanegrv 

![screenshot at oct 28 22-59-13](https://cloud.githubusercontent.com/assets/223620/10801254/8eee93c2-7dc7-11e5-8100-247c51109772.png)

**Comment by alexbaumgertner** [comment]
Нужно прописать background-color: white

**Comment by insanegrv** [comment]
Исправил в https://github.com/up-htmlacademy/61579-pink/pull/20

**Comment by alexbaumgertner** [comment]
:ok:
