### ISSUE TITLE
form: поправить legend

### ISSUE THREAD

**Issue by alexbaumgertner** [up-htmlacademy/61579-pink#19]
@insanegrv 

![screenshot at oct 28 23-04-44](https://cloud.githubusercontent.com/assets/223620/10801422/65a13de8-7dc8-11e5-8f53-3eed903175ca.png)

**Comment by alexbaumgertner** [comment]
Проверить на всех платформах

**Comment by alexbaumgertner** [comment]
Тут надо padding вроде сделать

**Comment by insanegrv** [comment]
Исправил в https://github.com/up-htmlacademy/61579-pink/pull/20

**Comment by alexbaumgertner** [comment]
:ok:
