### ISSUE TITLE
Поправить id у элементов svg

### ISSUE THREAD

**Issue by alexbaumgertner** [up-htmlacademy/61579-pink#9]
Ошибка: Duplicate ID Layer_1.

* https://validator.w3.org/nu/?doc=https%3A%2F%2Fup-htmlacademy.github.io%2F61579-pink%2F8%2F
* https://validator.w3.org/nu/?doc=https%3A%2F%2Fup-htmlacademy.github.io%2F61579-pink%2F8%2Fform.html

**Comment by alexbaumgertner** [comment]
@insanegrv

**Comment by insanegrv** [comment]
Исправил

**Comment by alexbaumgertner** [comment]
:ok:
